resources:
  - ../../base
  - namespace.yaml

namespace: patient-app-production

images:
  - name: jonasblum/image-to-be-replaced-depending-on-environment
    newName: jonasblum/patient-app-frontend-production
    newTag: latest

patches:
  - target:
      kind: Ingress
      name: patient-app-frontend-ingress
    path: patch-ingress.json
