import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import 'react-chatbot-kit/build/main.css';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <meta className="viewport" content="width=decive-width, initial-scale=1"/>
        </head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <div className="absolute top-4 left-4 text-2xl font-bold uppercase">
            <span className="text-3xl">P</span>atient&#39;s <span className="text-3xl">A</span>pp
        </div>
        {children}
        </body>
        </html>
    );
}
