import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import 'react-chatbot-kit/build/main.css';
import TranslationsProvider from "@/libs/provider/translation-provider";
import {ReactNode} from "react";
import initTranslations, {i18nNamespaces} from "@/libs/i18n/i18n";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface LayoutProps {
    children: ReactNode;
    params: Promise<{
        locale: string;
    }>;
}

export default async function RootLayout({
                                             children, params
                                         }: Readonly<LayoutProps>) {
    const {locale} = await params;
    const {resources} = await initTranslations(locale, i18nNamespaces);
    return (
        <html lang="en">
        <head>
            <meta className="viewport" content="width=decive-width, initial-scale=1"/>
        </head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <TranslationsProvider
            namespaces={i18nNamespaces}
            locale={locale}
            resources={resources}
        >
            <div className="absolute top-4 left-4 text-2xl font-bold uppercase">
                <span className="text-3xl">P</span>atient&#39;s <span className="text-3xl">A</span>pp
            </div>
            {children}
        </TranslationsProvider>
        </body>
        </html>
    );
}
