/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MessageOutputDTO
 */
export interface MessageOutputDTO {
    /**
     * 
     * @type {string}
     * @memberof MessageOutputDTO
     */
    'timestamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageOutputDTO
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageOutputDTO
     */
    'conversationId'?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageOutputDTO
     */
    'responseMessage'?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageOutputDTO
     */
    'requestMessage'?: string;
}

