/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PatientOutputDTO
 */
export interface PatientOutputDTO {
    /**
     * 
     * @type {string}
     * @memberof PatientOutputDTO
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatientOutputDTO
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatientOutputDTO
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatientOutputDTO
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatientOutputDTO
     */
    'language'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatientOutputDTO
     */
    'onboarded'?: boolean;
}

